version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: space_mission_db
    environment:
      POSTGRES_USER: space_admin
      POSTGRES_PASSWORD: space_password
      POSTGRES_DB: space_mission_control
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U space_admin -d space_mission_control" ]
      interval: 5s
      timeout: 5s
      retries: 5

  space-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: space_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/space_mission_control
      SPRING_DATASOURCE_USERNAME: space_admin
      SPRING_DATASOURCE_PASSWORD: space_password
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: